### PR TITLE
Feature/issues 163

### PR DESCRIPTION
**Pull request by Kronos11**
This adds in a default "To" value for the FromToToggle of DateTime.MaxValue

The idea is that the user wants the Toggle to be active from a point in time until it's disabled.

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

I'm on vacation! let me some days to check and review this PR

**Comment by Kronos11** [comment]
Accidentally deleted this branch re-opening, no worries and enjoy your vacation

**Comment by Kronos11** [comment]
@unaizorrilla Any thoughts on this? I understand if you would want to maybe just have a different Toggle for this, but it made sense if you don't put an end time on your toggle you would want it to go on until it was turned off.

**Comment by unaizorrilla** [comment]
Well, I can try to add new toggle for 4.X, this is not a breaking change and can be added easly

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

Looks good and make sense! , but after reviewing it I think we do this after adding a new feature about mandatory and optional parameters on toggles!

Let me do that first and I work on this when commited, I'm sorry for all the delay on this!

**Pull request closed without merging**
