### PR TITLE
Kronos11 feature/other db stores

### PR DESCRIPTION
**Pull request by Kronos11**
Continuing from #139

### CODE REVIEW

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

I try to review the builds, but, are you seeing my changes?  I'm planing to merge this for Esquio 4 branch ( this week )

**Comment by Kronos11** [comment]
> Hi @Kronos11
> 
> I try to review the builds, but, are you seeing my changes? I'm planing to merge this for Esquio 4 branch ( this week )

I'll review this today and try out the sample

**Comment by unaizorrilla** [comment]
OK, I'm releasing 3.1 ( minor changes, fix issue #131  on UI and update runtime, sdk) after this, master will be 4.0.0 :-)

**Comment by Kronos11** [comment]
Verified it's all looking good, if you accept my PR to this branch it should fix the github issues

**Comment by unaizorrilla** [comment]
Can I close this? Because is merged on Kronos11-feature/otherDbStores ??

**Comment by Kronos11** [comment]
> Can I close this? Because is merged on Kronos11-feature/otherDbStores ??

This is to merge into master for the 4.0 release right? I'm not sure what your branching strategy is.

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

this commits are merged on Xabaril:Kronos11-feature/otherDbStores with #143 !!

**Comment by Kronos11** [comment]
Correct, sorry I may not be understanding, but we can close this if you plan on doing a merge later with the Kronos11-feature/otherDbStores branch

**Comment by unaizorrilla** [comment]
Yeap after some more testing, I think PlotStatisticsRequestHandler is now working ok on Npgsql,  this branch will be merged and your commits honored in the history :-)

**Pull request closed without merging**
