### PR TITLE
Multiple data stores

### PR DESCRIPTION
**Pull request by Kronos11**
Adds in functionality for #137 
### What this PR does / why we need it:
This PR adds [Npgsql](https://github.com/npgsql/efcore.pg) as a separate database provider by creating a separate project for NpgSql and SqlServer

* [x] Add in Migrations for NpgSql
* [x] Update documentation
* [x] Unit Tests
* [x] Functional Tests

 Please make sure you've completed the relevant tasks for this PR, out of the following list:
 
 * [x]  Code compiles correctly
 * [x]  Created/updated tests
 * [x]  Unit tests passing
 * [x]  End-to-end tests passing
 * [x]  Add documentation
 * [ ]  Provided sample for the feature

### CODE REVIEW

**Comment by Kronos11** [comment]
A couple of questions:
@unaizorrilla 
1. Do we want SqlServer to be default and assume that by not requiring a UseSqlServer : true config?
2. Do we want to setup the docker file to include both postgres and sqlserver?
3. Do you want a sample project that uses postgres instead of sql server?

**Comment by Kronos11** [comment]
I'm not quite sure what's going on, the Functional tests are working for both on my machine with docker running, should be nearly identical. Looks to be something with Respawn trying to reset the db

**Comment by unaizorrilla** [comment]
Checking the error there is some strange, postgress functional tests are using SqlClient?  The origin is on Respawn Reset, probably respawn is not using postgress!

**Comment by Kronos11** [comment]
Fixed functional tests, I needed to set both env variables correctly

**Comment by unaizorrilla** [comment]
Can I review the PR?

**Comment by Kronos11** [comment]
Please do

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

I'm reviewing this! look good, I'm changing some things and when pushed we can discuss! 

For example, the first thing i'm planning to do is modify ServerFixture to simplify adding more DbProviders in future ( UseNpgsql  restrict only to npgsql or sqlserver )

thx again!

**Comment by Kronos11** [comment]
> Hi @Kronos11 
> 
> 
> 
> I'm reviewing this! look good, I'm changing some things and when pushed we can discuss! 
> 
> 
> 
> For example, the first thing i'm planning to do is modify ServerFixture to simplify adding more DbProviders in future ( UseNpgsql  restrict only to npgsql or sqlserver )
> 
> 
> 
> thx again!
> 
> 

Totally, I was actually planning on making that change depending on what you were thinking with the config. We could also have it `Store:Provider` and then the options could be SqlServer, NpgSql, etc which can then be const lookups or something similar. I can work on it tomorrow if you’re good with it?

**Comment by unaizorrilla** [comment]
Let me some days! I’m doing some Changes and pushing my commits

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

I create a branch from this PR with my changes 

https://github.com/Xabaril/Esquio/tree/Kronos11-feature/otherDbStores

Can you continue the PR on this branch? Close this and add your feedback on new branch?

My changes are :

 - Unify settings parameters to set the store and connection string, using the same for sqlserver, postgress and for next valid providers.
-  Execute booth functional tests ( sql and postgress ) on build.ps1 and build.sh
- Remove Stores project and move the content to api infrastructure data
- Fix settings on all yaml


Can you review this and continue the PR ( on this branch ) ? UI sample is not tested and probably need some customization on docker-compose ui to select the store to use etc

Thanks for all your work!!

**Comment by Kronos11** [comment]
closing and continuing on #141

**Pull request closed without merging**
