### PR TITLE
Bug/repro 157

### PR DESCRIPTION
**Pull request by Kronos11**

### CODE REVIEW

**Comment by Kronos11** [comment]
Reproduces exception in #157

**Comment by Kronos11** [comment]
Fixes bug by adding in a null check before adding anything to httpContextAccessor, Ideally if ScopedEvaluation is disabled we would use the NoScopedEvaluationHolder instead of the HttpScopedEvaluationHolder

**Comment by unaizorrilla** [comment]
Hi @Kronos11 

This PR also include the change of multiple subjects config, (this pr is pending to merge).. can you split on different PR's the fix for 157 and the multiple subject scenario?

**Comment by Kronos11** [comment]
Yup, sorry about that

**Comment by Kronos11** [comment]
closing

**Pull request closed without merging**
